export { AssistantsService } from './services/assistants.service';
export { DoctorsService } from './services/doctors.service';
export { ExaminationsService } from './services/examinations.service';
export { IcdService } from './services/icd.service';
export { PatientService } from './services/patient.service';
export { RegistrantsService } from './services/registrants.service';
export { SupervisorsService } from './services/supervisors.service';
export { UsersService } from './services/users.service';
export { VisitsService } from './services/visits.service';
